### ISSUE TITLE
APPLICATION ERROR #1406

### ISSUE THREAD

**Issue by steph2302** [YunoHost-Apps/mantis_ynh#14]
Bonjour à tous,

voici la description d'une erreur lors de l'accès à l'application Mantis. L'installation de Yunohost et de Mantis date de cet après-midi.

Auriez-vous une idée de la cause de cette erreur ?

### Describe the bug

Sur une installation toute fraîche de Yunohost, après installation de l'application Mantis Bug Tracker (depuis le gestionnaire d'applications). La tentative d'authentification affiche l'erreur suivante : 

**APPLICATION ERROR #1406

Impossible de lancer StartTLS sur le serveur LDAP.

Merci d'utiliser le bouton « Précédent » de votre navigateur web pour retourner à la page précédente. Vous pourrez y corriger les problèmes identifiés par cette erreur ou choisir une autre action. Vous pouvez aussi choisir une option de la barre de menu pour aller directement dans une nouvelle section.**

### Context

- Hardware: *VPS OVH*
- YunoHost version: 4.1.7.4 (stable)
- I have access to my server: *Through SSH | through the webadmin*
- certificat Let's encript valide

Merci d'avance

Stéphane

**Comment by jgeoffray69** [comment]
Bonjour,

Je rencontre le même problème, j'ai essayé plein de truc mais rien à faire.

Avez-vous trouver une solution ?

Merci d'avance

**Comment by steph2302** [comment]
Bonsoir,

non, je n'ai eu aucun retour d'autres utilisateurs ni trouvé de 
solution. J'ai laissé tombé Mantis Board pour le moment.

Désolé !

Stéphane

Le 31/03/2021 à 20:10, jgeoffray69 a écrit :

**Comment by jgeoffray69** [comment]
Bonjour,

Quelle solution utilisez vous pour la création de ticket ?

Cordialement



M. GEOFFRAY
633 Route de Cruisseau
01360 Béligneux


________________________________
De : steph2302 ***@***.***>
Envoyé : mercredi 31 mars 2021 21:38:37
À : YunoHost-Apps/mantis_ynh
Cc : jgeoffray69; Comment
Objet : Re: [YunoHost-Apps/mantis_ynh] APPLICATION ERROR #1406 (#14)


Bonsoir,

non, je n'ai eu aucun retour d'autres utilisateurs ni trouvé de
solution. J'ai laissé tombé Mantis Board pour le moment.

Désolé !

Stéphane

**Comment by jgeoffray69** [comment]
Bonjour J'ai trouvé la solution,
il faut rajouter ceci

#Authentification LDAP
$g_login_method = LDAP;
$g_ldap_use_starttls = OFF;
$g_reauthentication = ON;
$g_reauthentication_expiry = 600;
$g_ldap_server = 'ldap://Ip du serveur:389';
$g_ldap_root_dn = 'dc=nom de domaine,dc=extension';
$g_ldap_organization = '';
$g_ldap_protocol_version = 3;
$g_ldap_follow_referrals = OFF;
$g_ldap_bind_dn = 'cn="Nom utilisateur",ou="Ou de l'utilisateur",dc=nom de domaine,dc=extension';
$g_ldap_bind_passwd = "Votre mot de passe";
$g_use_ldap_realname = ON;
$g_use_ldap_email = ON;
$g_allow_blank_email = OFF;
$g_send_reset_password = ON; 
$g_ldap_uid_field ='sAMAccountName';
$g_ldap_realname_field='cn';
$g_log_level = LOG_WEBSERVICE;
$g_log_level = LOG_ALL;
$g_log_destination = 'C:\temp\mantisbt_LDAP.log';

**Comment by ericgaspar** [comment]
Sorry I haven't seen this issue... Thanks for pointing this out, It should be fixed with #15

**Comment by ericgaspar** [comment]
Closing with #15
