### ISSUE TITLE
APPLICATION ERROR #1404

### ISSUE THREAD

**Issue by ogrseca** [YunoHost-Apps/mantis_ynh#38]
Bonjour à tous,

Lors d'une mise à jour (Mantis ou Yunohost, je ne sais pas laquelle...), Mantis devient inaccessible :

"APPLICATION ERROR #1404
Extension LDAP non chargée.
Merci d'utiliser le bouton « Précédent » de votre navigateur web pour retourner à la page précédente. Vous pourrez y corriger les problèmes identifiés par cette erreur ou choisir une autre action. Vous pouvez aussi choisir une option de la barre de menu pour aller directement dans une nouvelle section."

Les blog Mantis orientent vers un problème LDAP du serveur...

Un problème d'intégration récent avec yunohost a-t-il été identifié ?

Yunohost : 11.2.10.3
Mantis : Version installée : 2.25.7~ynh1

Merci.

**Comment by maxlinux2000** [comment]
Same error here.

**Comment by ericgaspar** [comment]
shoild be fixed
